In [2]:
pip install psycopg2

Requirement already satisfied: psycopg2 in c:\users\admin\appdata\local\anaconda3\lib\site-packages (2.9.12)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import psycopg2

In [4]:
conn = psycopg2.connect(
        host="localhost",
        database="FS_Analysis",
        user="postgres",
        password="125890",
        port="5432"
    )
print("Connected to PostgreSQL!")

Connected to PostgreSQL!

In [5]:
query = ('''select
    "Company Symbol",
    "Element Name",
    "Value",
    "Decimal",
    "Taxonomy_Id"
from public."P&L YTD"
order by "Taxonomy_Id";''')

In [6]:
import pandas as pd
df = pd.read_sql_query(query, conn)
display(df)

C:\Users\admin\AppData\Local\Temp\ipykernel_5380\1696754556.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,Company Symbol,Element Name,Value,Decimal,Taxonomy_Id
0,STAR,RevenueFromOperations,1.083787e+10,-4.0,100200.101.9002.60026
1,STAR,RevenueFromOperations,1.409839e+10,-4.0,100200.101.9002.60026
2,ABB,RevenueFromOperations,3.054110e+10,-5.0,100200.101.9002.60026
3,ARE&M,RevenueFromOperations,1.038591e+11,-5.0,100200.101.9002.60026
4,ARE&M,RevenueFromOperations,1.038820e+11,-6.0,100200.101.9002.60026
...,...,...,...,...,...
567518,NTPC,InterestServiceCoverageRatio,4.000000e-02,inf,100200.101.9002.60067
567519,HCLTECH,InterestServiceCoverageRatio,0.000000e+00,inf,100200.101.9002.60067
567520,NTPC,InterestServiceCoverageRatio,4.000000e-02,inf,100200.101.9002.60067
567521,HATSUN,InterestServiceCoverageRatio,0.000000e+00,inf,100200.101.9002.60067
567522,HATSUN,InterestServiceCoverageRatio,0.000000e+00,inf,100200.101.9002.60067

In [7]:
df['Element_id'] = df['Taxonomy_Id'].str.rsplit('.', n=1).str[-1]
df['Element_id']
df

,Company Symbol,Element Name,Value,Decimal,Taxonomy_Id,Element_id
0,STAR,RevenueFromOperations,1.083787e+10,-4.0,100200.101.9002.60026,60026
1,STAR,RevenueFromOperations,1.409839e+10,-4.0,100200.101.9002.60026,60026
2,ABB,RevenueFromOperations,3.054110e+10,-5.0,100200.101.9002.60026,60026
3,ARE&M,RevenueFromOperations,1.038591e+11,-5.0,100200.101.9002.60026,60026
4,ARE&M,RevenueFromOperations,1.038820e+11,-6.0,100200.101.9002.60026,60026
...,...,...,...,...,...,...
567518,NTPC,InterestServiceCoverageRatio,4.000000e-02,inf,100200.101.9002.60067,60067
567519,HCLTECH,InterestServiceCoverageRatio,0.000000e+00,inf,100200.101.9002.60067,60067
567520,NTPC,InterestServiceCoverageRatio,4.000000e-02,inf,100200.101.9002.60067,60067
567521,HATSUN,InterestServiceCoverageRatio,0.000000e+00,inf,100200.101.9002.60067,60067
567522,HATSUN,InterestServiceCoverageRatio,0.000000e+00,inf,100200.101.9002.60067,60067

In [8]:
df.to_csv('D:/Telecommunication_Dashboard_Project/infi_2024.csv')

In [11]:
df3= pd.read_csv('D:/Telecommunication_Dashboard_Project/infi_2024.csv')
df3

,Unnamed: 0,Company Symbol,Element Name,Value,Decimal,Taxonomy_Id,Element_id
0,0,STAR,RevenueFromOperations,1.083787e+10,-4.0,100200.101.9002.60026,60026
1,1,STAR,RevenueFromOperations,1.409839e+10,-4.0,100200.101.9002.60026,60026
2,2,ABB,RevenueFromOperations,3.054110e+10,-5.0,100200.101.9002.60026,60026
3,3,ARE&M,RevenueFromOperations,1.038591e+11,-5.0,100200.101.9002.60026,60026
4,4,ARE&M,RevenueFromOperations,1.038820e+11,-6.0,100200.101.9002.60026,60026
...,...,...,...,...,...,...,...
567518,567518,NTPC,InterestServiceCoverageRatio,4.000000e-02,inf,100200.101.9002.60067,60067
567519,567519,HCLTECH,InterestServiceCoverageRatio,0.000000e+00,inf,100200.101.9002.60067,60067
567520,567520,NTPC,InterestServiceCoverageRatio,4.000000e-02,inf,100200.101.9002.60067,60067
567521,567521,HATSUN,InterestServiceCoverageRatio,0.000000e+00,inf,100200.101.9002.60067,60067
567522,567522,HATSUN,InterestServiceCoverageRatio,0.000000e+00,inf,100200.101.9002.60067,60067

In [12]:
df2 = df3.drop(columns=["Unnamed: 0", "row_num"], errors="ignore")
df2

,Company Symbol,Element Name,Value,Decimal,Taxonomy_Id,Element_id
0,STAR,RevenueFromOperations,1.083787e+10,-4.0,100200.101.9002.60026,60026
1,STAR,RevenueFromOperations,1.409839e+10,-4.0,100200.101.9002.60026,60026
2,ABB,RevenueFromOperations,3.054110e+10,-5.0,100200.101.9002.60026,60026
3,ARE&M,RevenueFromOperations,1.038591e+11,-5.0,100200.101.9002.60026,60026
4,ARE&M,RevenueFromOperations,1.038820e+11,-6.0,100200.101.9002.60026,60026
...,...,...,...,...,...,...
567518,NTPC,InterestServiceCoverageRatio,4.000000e-02,inf,100200.101.9002.60067,60067
567519,HCLTECH,InterestServiceCoverageRatio,0.000000e+00,inf,100200.101.9002.60067,60067
567520,NTPC,InterestServiceCoverageRatio,4.000000e-02,inf,100200.101.9002.60067,60067
567521,HATSUN,InterestServiceCoverageRatio,0.000000e+00,inf,100200.101.9002.60067,60067
567522,HATSUN,InterestServiceCoverageRatio,0.000000e+00,inf,100200.101.9002.60067,60067

In [15]:
import pandas as pd
import os
user_sector = input("Which Sector U want? (Example. Energy): ").strip()
user_igroup = input("Which Igroup U want?  (Example. Power Generation): ").strip()

conn.rollback() 

try:
    print(f"\n Sector: '{user_sector}' And Igroup: '{user_igroup}' Data Loading")
    
    whole_data_sql = """
    SELECT 
        ROW_NUMBER() OVER (ORDER BY c."Company Symbol" ASC, pl."Financial Year" DESC) AS row_num,
        
        -- १. Company 
        c."Company Symbol",
        c."Company Name",
        c."Sector" AS company_sector,
        c."Industry",
        c."Igroup",
        c."MarketCap",
        
        -- २. Financial Year & Quarter
        pl."Financial Year" AS financial_year,
        pl."Quarter" AS pl_quarter,
        
        -- ३. Taxonomy to Element Id
        (string_to_array(pl."Taxonomy_Id", '.'))[cardinality(string_to_array(pl."Taxonomy_Id", '.'))] AS element_id,
        pl."Taxonomy_Id" AS pl_taxonomy_id,
        
        -- ४. P&L YTD 
        pl."Element Name" AS pl_element_name,
        pl."Value" AS pl_value,
        CASE WHEN pl."Decimal" = '7' THEN '0' ELSE pl."Decimal" END AS pl_decimal,
        
        pl."Unit" AS pl_unit

    FROM public."Company" c
    LEFT JOIN public."P&L YTD" pl ON c."Company Symbol" = pl."Company Symbol"
    WHERE c."Sector" = %s AND c."Igroup" = %s;
    """
    chunks = pd.read_sql_query(whole_data_sql, conn, params=(user_sector, user_igroup), chunksize=10000)
    
    df_list = []
    for chunk in chunks:
        df_list.append(chunk)
        
    if len(df_list) > 0:
        df = pd.concat(df_list, ignore_index=True)
    else:
        df = pd.DataFrame() 
    
    if df.empty:
        print(f"Data Not Found Please check spelling")
    else:
        print(f"\n Data Fetch Successfully")
        folder_path = "D:/Telecommunication_Dashboard_Project"
        excel_file_path = f"{folder_path}/{user_sector}_{user_igroup}_data.xlsx"
        
        if not os.path.exists(folder_path):
            os.makedirs(folder_path)
            
        print("Excel file created")
        df.to_excel(excel_file_path, index=False, engine='openpyxl')
        
        print(f"Excel file saved in folder ")
        print(f"File Path: {excel_file_path}")

except Exception as e:
    print(f"Error Occuurs: {e}")

Which Sector U want? (Example. Energy):  Telecommunication
Which Igroup U want?  (Example. Power Generation):  Telecom - Services

⏳ Sector: 'Telecommunication' And Igroup: 'Telecom - Services' Data Loading

C:\Users\admin\AppData\Local\Temp\ipykernel_5380\1577863998.py:42: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  chunks = pd.read_sql_query(whole_data_sql, conn, params=(user_sector, user_igroup), chunksize=10000)

 Data Fetch Successfully
Excel file created
Excel file saved in folder
File Path: D:/Telecommunication_Dashboard_Project/Telecommunication_Telecom - Services_data.xlsx

In [16]:
import pandas as pd
import os
import re
from sqlalchemy import create_engine

# -----------------------------
# STEP 1: User Input
# -----------------------------
user_sector = input("Which Sector U want : ").strip()
user_igroup = input("Which Igroup U want: ").strip()

# Creating a clean database table name by removing special characters and spaces
# E.g., 'Energy and Power Generation' becomes 'pnl_energy_power_generation'
clean_sector = re.sub(r'[^a-zA-Z0-9_]', '', user_sector.lower().replace(' ', '_'))
clean_igroup = re.sub(r'[^a-zA-Z0-9_]', '', user_igroup.lower().replace(' ', '_'))
target_table_name = f"pnl_{clean_sector}_{clean_igroup}"

username = "postgres"
password = "125890"
host = "localhost"
port = "5432"
database = "FS_Analysis"

# Creating a SQLAlchemy Engine
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# -----------------------------
# STEP 2: Data Fetching Clause (your original SQL)
# -----------------------------
conn.rollback() # Rollback of your original connection

try:
    print(f"\n⏳ Sector: '{user_sector}' And Igroup: '{user_igroup}' Data Loading from Database...")
    
    whole_data_sql = """
    SELECT 
        ROW_NUMBER() OVER (ORDER BY c."Company Symbol" ASC, pl."Financial Year" DESC) AS row_num,
        
        -- १. Company 
        c."Company Symbol",
        c."Company Name",
        c."Sector" AS company_sector,
        c."Industry",
        c."Igroup",
        c."MarketCap",
        
        -- ②. Financial Year & Quarter
        pl."Financial Year" AS financial_year,
        pl."Quarter" AS pl_quarter,
        
        -- ③. Taxonomy to Element Id
        (string_to_array(pl."Taxonomy_Id", '.'))[cardinality(string_to_array(pl."Taxonomy_Id", '.'))] AS element_id,
        pl."Taxonomy_Id" AS pl_taxonomy_id,
        
        -- ④. P&L YTD 
        pl."Element Name" AS pl_element_name,
        pl."Value" AS pl_value,
        CASE WHEN pl."Decimal" = '7' THEN '0' ELSE pl."Decimal" END AS pl_decimal,
        
        pl."Unit" AS pl_unit

    FROM public."Company" c
    LEFT JOIN public."P&L YTD" pl ON c."Company Symbol" = pl."Company Symbol"
    WHERE c."Sector" = %s AND c."Igroup" = %s;
    """
    
    # Reading data in chunks
    chunks = pd.read_sql_query(whole_data_sql, conn, params=(user_sector, user_igroup), chunksize=10000)
    
    df_list = []
    for chunk in chunks:
        df_list.append(chunk)
        
    if len(df_list) > 0:
        df = pd.concat(df_list, ignore_index=True)
    else:
        df = pd.DataFrame() 
    
    if df.empty:
        print(f" Data Not Found! Please check spelling of Sector or Igroup.")
    else:
        print(f" Data Fetched Successfully! Total Rows: {len(df)}")
        print(f" Creating and Loading table '{target_table_name}' into PostgreSQL...")
        
        # Pushing data directly to SQL instead of Excel (using `if_exists='replace'` will overwrite the existing table if it exists)
        df.to_sql(
            name=target_table_name, 
            con=engine, 
            schema="public", 
            if_exists="replace", 
            index=False
        )
        
        print(f"Successfully'{target_table_name}' name table created")

except Exception as e:
    print(f" Error Occurs: {e}")

Which Sector U want :  Telecommunication
Which Igroup U want:  Telecom - Services

⏳ Sector: 'Telecommunication' And Igroup: 'Telecom - Services' Data Loading from Database...

C:\Users\admin\AppData\Local\Temp\ipykernel_5380\1986771658.py:68: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  chunks = pd.read_sql_query(whole_data_sql, conn, params=(user_sector, user_igroup), chunksize=10000)

 Data Fetched Successfully! Total Rows: 9162
 Creating and Loading table 'pnl_telecommunication_telecom__services' into PostgreSQL...
Successfully'pnl_telecommunication_telecom__services' name table created

In [17]:
# -------------------------------------------------------------------
# Creating an Excel file named after the database table (target_table_name)
# -------------------------------------------------------------------
try:
    if not df.empty:
       # Setting the Excel file name to match the database table name (e.g., pnl_energy_oil.xlsx)
        exact_excel_file_path = f"{folder_path}/{target_table_name}.xlsx"
        
        # Create the folder if it does not exist
        if not os.path.exists(folder_path):
            os.makedirs(folder_path)
            
        print(f"\n Generating Excel file at: {exact_excel_file_path}...")
        
        df.to_excel(exact_excel_file_path, index=False, engine='openpyxl')
        
        print(f"Excel file saved successfully!")
        print(f"File name and path: {exact_excel_file_path}")
    else:
        print("\nCould not create the Excel file because the data frame is empty..")

except Exception as e:
    print(f"An error occurred while creating the Excel file.: {e}")

 Generating Excel file at: D:/Telecommunication_Dashboard_Project/pnl_telecommunication_telecom__services.xlsx...
Excel file saved successfully!
File name and path: D:/Telecommunication_Dashboard_Project/pnl_telecommunication_telecom__services.xlsx